name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_database: ^12.0.4
  firebase_storage: ^13.0.4
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flyers/
